# Base configs
baseurl: /profileflat

# UI configs
title: "KSHITIJ GUPTA"
author: "KSHITIJ GUPTA"
about: "NOT A PROGRAMMER"
social_urls:
  facebook: "https://www.facebook.com/kshitijgupta"
  twitter: "https://www.twitter.com/mkshitijgupta965"
  instagram: "https://www.instagram.com/kshitij.gupta965"
